### ISSUE TITLE
No one direction sign

### ISSUE THREAD

**Issue by de-vries** [mapillary/traffico#24]
I'm missing this sign:
![oneway](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Nederlands_verkeersbord_C3.svg/200px-Nederlands_verkeersbord_C3.svg.png)
source: https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_C3.svg

there is this one, but it has a different meaning:
![notoneway](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Nederlands_verkeersbord_D4.svg/200px-Nederlands_verkeersbord_D4.svg.png)
source: https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_D4.svg

**Comment by mprins** [comment]
if no-one beats me to it I can have ago at this like wednesday or so
