### ISSUE TITLE
Pedestrian crossing

### ISSUE THREAD

**Issue by de-vries** [mapillary/traffico#25]
I'm missing this sign:
![1](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Nederlands_verkeersbord_J22.svg/200px-Nederlands_verkeersbord_J22.svg.png)
source: https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_J22.svg

there is this one, but it has a different meaning:
![2](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Nederlands_verkeersbord_L2.svg/200px-Nederlands_verkeersbord_L2.svg.png)
source: https://commons.wikimedia.org/wiki/File:Nederlands_verkeersbord_L2.svg

**Comment by mprins** [comment]
if no-one beats me to it I can have ago at this like wednesday or so
