### ISSUE TITLE
Dutch signs

### ISSUE THREAD

**Issue by floscher** [mapillary/traffico#29]
Continues discussion from mapillary/mapillary_issues#568.

@Peatsmoke As traffico represents the signs not as SVG files but as an icon font (made out of simpler SVG icons), SVG files of complete signs could serve as a template, but would need to be recreated. Currently we use e.g. http://en.wikipedia.org/wiki/Road_signs_in_the_Netherlands and the pages linked at the bottom of that page. But it will take some time to add all European signs.

Is your collection of signs online available somewhere?

Thanks for your effort!

**Comment by mprins** [comment]
this has all dutch traffic signs as registered in relevant law: http://wetten.overheid.nl/BWBR0004825/Bijlage1/tekst_bevat_verkeersborden/geldigheidsdatum_23-02-2015

**Comment by Peatsmoke** [comment]
Sorry, don't have them online. Honesty I think this take too much time for me, to learn al this. I think I can be more usefull by reviewing traffic-signs and collecting pictures... ;)
