### ISSUE TITLE
idea: automatically build on travis

### ISSUE THREAD

**Issue by mprins** [mapillary/traffico#33]
this: https://github.com/Bartvds/demo-travis-gh-pages decsribes a way to automatically build on travis-ci and push back to the gh-pages branch

I think it makes a "nice to have" feature if this is set up on the master branch; it would automatically push the latest succesful build of master back to the website.

**Comment by mprins** [comment]
some other examples:

  - https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db
  - http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/
  - http://www.r-bloggers.com/travis-ci-to-github-pages/

**Comment by knikel** [comment]
Love this idea, thanks @mprins! I will look into that and implement it in the coming days.

**Comment by floscher** [comment]
Good idea! I also tried to set up Travis for traffico (for the master-branch), but gave up quite soon. IIRC the reason, why I gave it up had something to do with sudo-privileges that are required when setting up traffico.

See 4b3fa7a for my Travis configuration (I believe I've enhanced it since that version, but can't find it anymore).

**Comment by mprins** [comment]
AFAIK all travis buildboxes support passwordless sudo, you may however need to install node_legacy instead of node js (I've had to do this on both mint and ubuntu linuxes)

**Comment by floscher** [comment]
No, not all. As far as I remember it was some issue with the container-based Travis infrastructure, which does not allow sudo.
Node is no problem, as it is already preinstalled (at least when adding `node_js: "0.10"` to .travis.yml).

But anyway, I've tried again and was able to build the master branch in Travis without problems (see 22ba695 and [the corresponding Travis build](https://travis-ci.org/floscher/traffico/builds/51917815).

**Comment by knikel** [comment]
Thanks for all the amazing help with this @floscher. I think we can deem this as fixed. You rock!
