### ISSUE TITLE
Bump vs Bumpiness

### ISSUE THREAD

**Issue by de-vries** [mapillary/traffico#34]
there is no speed bump sign:
![bump](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Nederlands_verkeersbord_J38.svg/200px-Nederlands_verkeersbord_J38.svg.png)
[source](https://en.wikipedia.org/wiki/File:Nederlands_verkeersbord_J38.svg)
The icon for this is missing as well

There is this sign:
![bumpiness](https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Nederlands_verkeersbord_J1.svg/200px-Nederlands_verkeersbord_J1.svg.png)
[source](https://en.wikipedia.org/wiki/File:Nederlands_verkeersbord_J1.svg)
But it means uneven road. confusingly the icon in this sign is called [bump.svg
](https://github.com/mapillary/traffico/blob/master/icons/bump.svg).
The uneven road sign gets used in Mapillary to tag speed bump signs all the time.

**Comment by de-vries** [comment]
sorry over looked some things...

**Comment by knikel** [comment]
@de-vries yes, we will update Mapillary with new signs again soon.

**Comment by waldyrious** [comment]
Why is this issue closed? It doesn't seem to have been fixed yet.

**Comment by floscher** [comment]
It has been fixed in [`c9d1732`](https://github.com/mapillary/traffico/commit/c9d17320b09ad1b1d6eeb27558a6157a8f21e5d8#diff-54b73aa4b045ff867ca21738067a6b52R232) and included in [v0.1.1](https://github.com/mapillary/traffico-release/releases/tag/v0.1.1)

**Comment by waldyrious** [comment]
Ah, thanks @floscher :)
