### ISSUE TITLE
recognise living zone on/off signs

### ISSUE THREAD

**Issue by richlv** [mapillary/traffico#36]
living zone/street signs are not recognised currently. they do differ somewhat from country to country, though.

http://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street

latvian version can be seen here : http://www.csdd.lv/lat/noderiga_informacija/satiksmes_drosiba_berniem/velosipedu_vaditaji_/pamatpienakumi_velobraucejiem/dzivojama_zona/

**Comment by knikel** [comment]
This issue has been moved to https://github.com/mapillary/mapillary_sprite_source/issues/6
