### ISSUE TITLE
Sign for speed-/traffic cam

### ISSUE THREAD

**Issue by EOSfoto** [mapillary/traffico#45]
Would it be possible to create a sign for physic speed- or traffic cam?

**Comment by pyrog** [comment]
:+1: Good idea

**Comment by Caboosey** [comment]
@knikel Here examples of US signs for photo enforcement traffic lights (AKA "Red Light Cameras"):

Note: Not all the signs on the streets will include "Includes right turn" or "Includes left turn"
**Current** Red light Camera (40 MPH or more) Sign:
http://www.dot.state.fl.us/trafficoperations/TrafficServices/SignLibrary/Regulatory/Reg_Bmp/R10-18a.bmp
http://mutcd.fhwa.dot.gov/resources/interim_approval/ia12/images/figia12_longdesc.jpg
**Current** Red Light Camera (Under 40 MPH) Sign:
http://www.dot.state.fl.us/trafficoperations/TrafficServices/SignLibrary/Regulatory/Reg_Bmp/FTP%20-%20TRAFFIC%20PHOTO%20ENFORCED%20MIN.bmp

**Older/Other** Red Light Camera signs:
http://blog.photoenforced.com/2011/02/red-light-camera-warning-signs.html

**Comment by Caboosey** [comment]
@knikel Here is UK's red light camera signs and speed camera signs:
https://www.avonandsomerset.police.uk/media/20890607/tsrgd-signs-2-.jpg

**Comment by knikel** [comment]
Thanks @Caboosey, will add in the next round of adding signs!

**Comment by knikel** [comment]
This issue has been moved to https://github.com/mapillary/mapillary_sprite_source/issues/6
