### ISSUE TITLE
Missing sign : Domestic animals

### ISSUE THREAD

**Issue by pyrog** [mapillary/traffico#47]
![](http://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/France_road_sign_A15a1.svg/60px-France_road_sign_A15a1.svg.png)
See http://en.wikipedia.org/wiki/Comparison_of_European_road_signs#Warning

Could you add it please ?

**Comment by peterneubauer** [comment]
Wanna do an SVG for it and a PR @pyrog ?

**Comment by pyrog** [comment]
You could find it (and a lot of missing signs) in SVG from the wikipedia page :wink: 

> Wanna do an SVG for it

http://commons.wikimedia.org/wiki/File:France_road_sign_A15a1.svg

> and a PR

Sorry, I don't know how to "cut" the cow and resize it from this file.

**Comment by floscher** [comment]
This can be closed now (see #48).
