### ISSUE TITLE
Latin America signs for parking

### ISSUE THREAD

**Issue by nighto** [mapillary/traffico#52]
Brazilian signs are pretty much equal to US signs, with a single exception: parking related signs. Whether it's allowed or forbidden to park or stop, it's the letter `E` (of "estacionamento") instead of `P`.

![Proibido Estacionar](http://www.blogtransitar.com.br/v1/wp-content/uploads/2014/06/Placas.jpg)

A quick search for "prohibido estacionar" revealed that in Latin America countries that speaks spanish it is pretty much the same.

So it'd be very simple to make the first l10n for the project, creating a class similar to `.t-parking` with a letter E instead of P. Could be `.t-parking-e` or `.t-estacionar`. (I think I prefer the first one.)

**Comment by jesolem** [comment]
@knikel Close this one? We deployed this already, right?

**Comment by knikel** [comment]
@jesolem yes, these have been added to traffico, thanks!
