### ISSUE TITLE
French maxspeed end

### ISSUE THREAD

**Issue by operon** [mapillary/traffico#57]
The maxspeed is detected by mapillary but the end is no detected.
For french :
https://commons.wikimedia.org/wiki/File:France_road_sign_B33_(50).svg

in th e code , just question :
{ type: 'circle-bg', color: 'white', transform: '{fit_border_circle}' }
or
{ type: 'circle-bg', color: 'white', transform: 'scale(.95)' }

prohibitory_speed_limit_end:
  category: 'prohibitory'
  name: 'end of speed limit ref:B33'
  elements: [
    { type: 'circle-bg', color: 'black' }
    { type: 'circle-bg', color: 'white', transform: '{fit_border_circle}' }
    { type: 'circle-bar-rounded', color: 'black', transform: 'rotate(45deg)'}
    { type: 'speed_value', color: 'white' }
    { type: 'speed_value', color: 'black', transform: 'scale(.8)' }
    ]

**Comment by floscher** [comment]
>in the code , just question :
{ type: 'circle-bg', color: 'white', transform: '{fit_border_circle}' }
or
{ type: 'circle-bg', color: 'white', transform: 'scale(.95)' }

According to [transformations.cson](https://github.com/mapillary/traffico/blob/9c6792a7c8853f287596f48ae279c9e6368d0052/stylesheets/transformations.cson), `{fit_border_circle}` is just an alias for `scale(.8)` which produces a thicker border like for `prohibitory_pedestrian`, so probably `scale(.95)` would be the better choice.

Your suggestion
```cson
prohibitory_speed_limit_end:
  category: 'prohibitory'
  name: 'end of speed limit ref:B33'
  elements: [
    { type: 'circle-bg', color: 'black' }
    { type: 'circle-bg', color: 'white', transform: '{fit_border_circle}' }
    { type: 'circle-bar-rounded', color: 'black', transform: 'rotate(45deg)'}
    { type: 'speed_value', color: 'white' }
    { type: 'speed_value', color: 'black', transform: 'scale(.8)' }
  ]
```
produces the following result:
![french_speed_limit_end](https://cloud.githubusercontent.com/assets/3904348/8697121/cc34baf4-2af2-11e5-85d5-bb9fceceefec.png)

One problem with this is that scaling text also scales the space in between the characters so the two scaled text-layers don't align well.

Currently traffico doesn't provide an easy way to add a border to text. So I'd propose a slightly different approach:
```cson
prohibitory_speed_limit_end:
  category: 'prohibitory'
  name: 'end of speed limit ref:B33'
  elements: [
    { type: 'circle-bg', color: 'black' }
    { type: 'circle-bg', color: 'white', transform: 'scale(.95)' }
    { type: 'circle-bar-rounded', color: 'black', transform: 'rotate(45deg)'}
    { type: 'circle-bg', color: 'white', transform: 'scale(.5)' }
    { type: 'speed_value', color: 'black', transform: 'scale(.8) translate(0,-7%)' }
  ]
```
![french_speed_limit_end_2](https://cloud.githubusercontent.com/assets/3904348/8697321/51ab1ad8-2af4-11e5-8ce2-deff865382a6.png)

**Comment by floscher** [comment]
@operon just as a sidenote:
When writing code in GitHub Issues or pull requests, it is much more readable, if you surround your code with three backticks (`) before and another three backticks after your code snippet.

Even better would be, if you created a pull request (it's easier than it sounds, at least here on github). Simply go to the file that you want to modify (https://github.com/mapillary/traffico/blob/master/dev/fr.cson), click on the pencil-icon in the top right corner of the file.
Then make the changes you want to propose, add a comment in the field at the bottom and click on `Propose file change`.
You then see the changes you made, if you're happy with them, click on `Create pull request`.

When you want to propose concrete code changes, pull requests offer better posibilities to discuss and comment code changes.

**Comment by operon** [comment]
Hi,
      
      Thanks, i test it later for new idea
      
      
      Le 15/07/2015 13:39, Florian Schäfer a écrit :
    
    
      @operon just as a sidenote:
        When writing code in GitHub Issues or pull requests, it is much
        more readable, if you surround your code with three backticks
        (`) before and another three backticks after your code snippet.
      Even better would be, if you created a pull request (it's
        easier than it sounds, at least here on github). Simply go to
        the file that you want to modify (https://github.com/mapillary/traffico/blob/master/dev/fr.cson),
        click on the pencil-icon in the top right corner of the file.
        Then make the changes you want to propose, add a comment in the
        field at the bottom and click on Propose file change.
        You then see the changes you made, if you're happy with them,
        click on Create pull request.
      When you want to propose concrete code changes, pull requests
        offer better posibilities to discuss and comment code changes.
      —
        Reply to this email directly or view
          it on GitHub.
